# Generated by Django 2.0.3 on 2018-03-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommate',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=None, to='roommates_app.Apartment'),
        ),
    ]
