# Generated by Django 2.0.3 on 2018-03-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommates_app', '0003_auto_20180330_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='roommate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates_app.Roommate'),
        ),
        migrations.AlterField(
            model_name='roommate',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roommates_app.Apartment'),
        ),
    ]
