# Generated by Django 2.0.3 on 2018-03-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommates_app', '0004_auto_20180330_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roommates_app.Apartment'),
        ),
    ]
