# Generated by Django 2.0.3 on 2018-03-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates_app', '0006_auto_20180330_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='roommate',
            old_name='user',
            new_name='account',
        ),
    ]
