# Generated by Django 2.0.3 on 2018-03-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates_app', '0008_auto_20180330_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
