# Generated by Django 2.0.3 on 2018-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates_app', '0009_cleaning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommate',
            name='colour',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
