# Generated by Django 2.0.3 on 2018-03-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates_app', '0010_roommate_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='date',
        ),
        migrations.AddField(
            model_name='cleaning',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
